# Session – 14

# Advanced Text Cleaning & Duplicate Resolution with Pandas

In [22]:
import pandas as pd

# Task 1: The Record Reconciler (Duplicate Identification & Resolution)

In [23]:
customers = pd.read_csv("customers-1000.csv")

print("Dataset Shape:",customers.shape)
print("Columns:",customers.columns.tolist())

customers.head()

Dataset Shape: (1000, 12)
Columns: ['Index', 'Customer Id', 'First Name', 'Last Name', 'Company', 'City', 'Country', 'Phone 1', 'Phone 2', 'Email', 'Subscription Date', 'Website']

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,dE014d010c7ab0c,Andrew,Goodman,Stewart-Flynn,Rowlandberg,Macao,846-790-4623x4715,(422)787-2331x71127,marieyates@gomez-spencer.info,2021-07-26,http://www.shea.biz/
1,2,2B54172c8b65eC3,Alvin,Lane,"Terry, Proctor and Lawrence",Bethside,Papua New Guinea,124-597-8652x05682,321.441.0588x6218,alexandra86@mccoy.com,2021-06-24,http://www.pena-cole.com/
2,3,d794Dd48988d2ac,Jenna,Harding,Bailey Group,Moniquemouth,China,(335)987-3085x3780,001-680-204-8312,justincurtis@pierce.org,2020-04-05,http://www.booth-reese.biz/
3,4,3b3Aa4aCc68f3Be,Fernando,Ford,Moss-Maxwell,Leeborough,Macao,(047)752-3122,048.779.5035x9122,adeleon@hubbard.org,2020-11-29,http://www.hebert.com/
4,5,D60df62ad2ae41E,Kara,Woods,Mccarthy-Kelley,Port Jacksonland,Nepal,+1-360-693-4419x19272,163-627-2565,jesus90@roberson.info,2022-04-22,http://merritt.com/

In [24]:
# Create Customer_Email column
customers["Customer_Email"] = customers["Email"]


# Simulate duplicate email records
customers.loc[5, "Customer_Email"] = customers.loc[0, "Customer_Email"]
customers.loc[10, "Customer_Email"] = customers.loc[0, "Customer_Email"]


# Create an Updated_Date column
customers["Updated_Date"] = pd.date_range(
    start="2024-01-01",
    periods=len(customers),
    freq="D"
)


# Give the duplicate records newer dates
customers.loc[5, "Updated_Date"] = pd.Timestamp("2025-01-01")
customers.loc[10, "Updated_Date"] = pd.Timestamp("2025-02-01")

customers.head(11)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website,Customer_Email,Updated_Date
0,1,dE014d010c7ab0c,Andrew,Goodman,Stewart-Flynn,Rowlandberg,Macao,846-790-4623x4715,(422)787-2331x71127,marieyates@gomez-spencer.info,2021-07-26,http://www.shea.biz/,marieyates@gomez-spencer.info,2024-01-01
1,2,2B54172c8b65eC3,Alvin,Lane,"Terry, Proctor and Lawrence",Bethside,Papua New Guinea,124-597-8652x05682,321.441.0588x6218,alexandra86@mccoy.com,2021-06-24,http://www.pena-cole.com/,alexandra86@mccoy.com,2024-01-02
2,3,d794Dd48988d2ac,Jenna,Harding,Bailey Group,Moniquemouth,China,(335)987-3085x3780,001-680-204-8312,justincurtis@pierce.org,2020-04-05,http://www.booth-reese.biz/,justincurtis@pierce.org,2024-01-03
3,4,3b3Aa4aCc68f3Be,Fernando,Ford,Moss-Maxwell,Leeborough,Macao,(047)752-3122,048.779.5035x9122,adeleon@hubbard.org,2020-11-29,http://www.hebert.com/,adeleon@hubbard.org,2024-01-04
4,5,D60df62ad2ae41E,Kara,Woods,Mccarthy-Kelley,Port Jacksonland,Nepal,+1-360-693-4419x19272,163-627-2565,jesus90@roberson.info,2022-04-22,http://merritt.com/,jesus90@roberson.info,2024-01-05
5,6,8aaa5d0CE9ee311,Marissa,Gamble,Cherry and Sons,Webertown,Sudan,001-645-334-5514x0786,(751)980-3163,katieallison@leonard.com,2021-11-17,http://www.kaufman.org/,marieyates@gomez-spencer.info,2025-01-01
6,7,73B22Ac8A43DD1A,Julie,Cooley,"Yu, Norman and Sharp",West Sandra,Japan,+1-675-243-7422x9177,(703)337-5903,priscilla88@stephens.info,2022-03-26,http://www.sexton-chang.com/,priscilla88@stephens.info,2024-01-07
7,8,DC94CCd993D311b,Lauren,Villa,"French, Travis and Hensley",New Yolanda,Fiji,081.226.1797x647,186.540.9690x605,colehumphrey@austin-caldwell.com,2020-08-14,https://www.kerr.com/,colehumphrey@austin-caldwell.com,2024-01-08
8,9,9Ba746Cb790FED9,Emily,Bryant,"Moon, Strickland and Combs",East Normanchester,Seychelles,430-401-5228x35091,115-835-3840,buckyvonne@church-lutz.com,2020-12-30,http://grimes.com/,buckyvonne@church-lutz.com,2024-01-09
9,10,aAa1EDfaA70DA0c,Marie,Estrada,May Inc,Welchton,United Arab Emirates,001-648-790-9244,973-767-3611,christie44@mckenzie.biz,2020-09-03,https://www.salinas.net/,christie44@mckenzie.biz,2024-01-10
10,11,bf104C25d0BA4E1,Nichole,Cannon,Rios and Sons,West Devon,Burundi,0647787401,139.476.1068,blandry@henson-harris.biz,2021-04-26,http://www.humphrey.org/,marieyates@gomez-spencer.info,2025-02-01

In [25]:
# Identify all duplicate Customer_Email records
duplicates = customers[
    customers.duplicated(
        subset="Customer_Email",
        keep=False
    )
]

display(duplicates)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website,Customer_Email,Updated_Date
0,1,dE014d010c7ab0c,Andrew,Goodman,Stewart-Flynn,Rowlandberg,Macao,846-790-4623x4715,(422)787-2331x71127,marieyates@gomez-spencer.info,2021-07-26,http://www.shea.biz/,marieyates@gomez-spencer.info,2024-01-01
5,6,8aaa5d0CE9ee311,Marissa,Gamble,Cherry and Sons,Webertown,Sudan,001-645-334-5514x0786,(751)980-3163,katieallison@leonard.com,2021-11-17,http://www.kaufman.org/,marieyates@gomez-spencer.info,2025-01-01
10,11,bf104C25d0BA4E1,Nichole,Cannon,Rios and Sons,West Devon,Burundi,0647787401,139.476.1068,blandry@henson-harris.biz,2021-04-26,http://www.humphrey.org/,marieyates@gomez-spencer.info,2025-02-01

In [26]:
# Sort by Updated_Date so the newest record comes last
customers_sorted = customers.sort_values("Updated_Date")


# Remove duplicate Customer_Email values, keeping the most recent record
clean_customers = customers_sorted.drop_duplicates(
    subset="Customer_Email",
    keep="last"
)

print("Original number of records:", len(customers))
print("Records after removing duplicates:", len(clean_customers))

display(clean_customers.head(11))

Original number of records: 1000
Records after removing duplicates: 998

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website,Customer_Email,Updated_Date
1,2,2B54172c8b65eC3,Alvin,Lane,"Terry, Proctor and Lawrence",Bethside,Papua New Guinea,124-597-8652x05682,321.441.0588x6218,alexandra86@mccoy.com,2021-06-24,http://www.pena-cole.com/,alexandra86@mccoy.com,2024-01-02
2,3,d794Dd48988d2ac,Jenna,Harding,Bailey Group,Moniquemouth,China,(335)987-3085x3780,001-680-204-8312,justincurtis@pierce.org,2020-04-05,http://www.booth-reese.biz/,justincurtis@pierce.org,2024-01-03
3,4,3b3Aa4aCc68f3Be,Fernando,Ford,Moss-Maxwell,Leeborough,Macao,(047)752-3122,048.779.5035x9122,adeleon@hubbard.org,2020-11-29,http://www.hebert.com/,adeleon@hubbard.org,2024-01-04
4,5,D60df62ad2ae41E,Kara,Woods,Mccarthy-Kelley,Port Jacksonland,Nepal,+1-360-693-4419x19272,163-627-2565,jesus90@roberson.info,2022-04-22,http://merritt.com/,jesus90@roberson.info,2024-01-05
6,7,73B22Ac8A43DD1A,Julie,Cooley,"Yu, Norman and Sharp",West Sandra,Japan,+1-675-243-7422x9177,(703)337-5903,priscilla88@stephens.info,2022-03-26,http://www.sexton-chang.com/,priscilla88@stephens.info,2024-01-07
7,8,DC94CCd993D311b,Lauren,Villa,"French, Travis and Hensley",New Yolanda,Fiji,081.226.1797x647,186.540.9690x605,colehumphrey@austin-caldwell.com,2020-08-14,https://www.kerr.com/,colehumphrey@austin-caldwell.com,2024-01-08
8,9,9Ba746Cb790FED9,Emily,Bryant,"Moon, Strickland and Combs",East Normanchester,Seychelles,430-401-5228x35091,115-835-3840,buckyvonne@church-lutz.com,2020-12-30,http://grimes.com/,buckyvonne@church-lutz.com,2024-01-09
9,10,aAa1EDfaA70DA0c,Marie,Estrada,May Inc,Welchton,United Arab Emirates,001-648-790-9244,973-767-3611,christie44@mckenzie.biz,2020-09-03,https://www.salinas.net/,christie44@mckenzie.biz,2024-01-10
11,12,bf2fA37cbAd7dDc,Bernard,Ritter,Bradford and Sons,West Francisco,Palau,292.313.1902,(065)075-0554,tammiepope@arroyo-baldwin.com,2022-01-19,http://sellers.biz/,tammiepope@arroyo-baldwin.com,2024-01-12
12,13,4fa8ffcdBbf53bB,Darryl,Archer,Kerr-Cherry,Holtfurt,Uganda,(389)437-1716,092.364.7349x593,woodalejandro@skinner-sloan.biz,2022-04-18,https://www.daniels.com/,woodalejandro@skinner-sloan.biz,2024-01-13
13,14,aBd960429ecd363,Ryan,Li,"Hooper, Cross and Holt",Batesville,Liechtenstein,001-119-787-0125x4500,001-477-254-3645,lmassey@duke.com,2021-03-06,http://nunez.com/,lmassey@duke.com,2024-01-14

# Impact of keep parameter in drop_duplicates()

- `keep='first'`: Keeps the first occurrence of each duplicate record and removes the later duplicates.

- `keep='last'`: Keeps the last occurrence of each duplicate record and removes the earlier duplicates. In this task, sorting by `Updated_Date` first allows us to keep the most recent record.

- `keep=False`: Removes all records that have duplicates. It does not keep any occurrence of the duplicated records.

# Task 2: The Text Normalizer (String Standardization)

In [27]:
import pandas as pd

products = pd.read_csv("products.csv")

print("Dataset Shape:", products.shape)
print("Columns:", products.columns.tolist())

products.head()

Dataset Shape: (295, 4)
Columns: ['ProductID', 'ProductName', 'Category', 'ListPrice']

   ProductID              ProductName        Category  ListPrice
0        771  Mountain-100 Silver, 38  Mountain Bikes    3399.99
1        772  Mountain-100 Silver, 42  Mountain Bikes    3399.99
2        773  Mountain-100 Silver, 44  Mountain Bikes    3399.99
3        774  Mountain-100 Silver, 48  Mountain Bikes    3399.99
4        775   Mountain-100 Black, 38  Mountain Bikes    3374.99

In [28]:
# Convert ProductName to lowercase
products["ProductName"] = products["ProductName"].str.lower()

products.head()

   ProductID              ProductName        Category  ListPrice
0        771  mountain-100 silver, 38  Mountain Bikes    3399.99
1        772  mountain-100 silver, 42  Mountain Bikes    3399.99
2        773  mountain-100 silver, 44  Mountain Bikes    3399.99
3        774  mountain-100 silver, 48  Mountain Bikes    3399.99
4        775   mountain-100 black, 38  Mountain Bikes    3374.99

In [29]:
# Find products containing the word "pro"
pro_products = products[
    products["ProductName"].str.contains("pro", na=False)
]

display(pro_products)

     ProductID                ProductName Category  ListPrice
279        848  headlights - weatherproof   Lights      44.99

In [30]:
# Create Is_Premium_Product column
products["Is_Premium_Product"] = products["ProductName"].str.contains(
    "pro",
    na=False
)

display(products)

,ProductID,ProductName,Category,ListPrice,Is_Premium_Product
0,771,"mountain-100 silver, 38",Mountain Bikes,3399.99,False
1,772,"mountain-100 silver, 42",Mountain Bikes,3399.99,False
2,773,"mountain-100 silver, 44",Mountain Bikes,3399.99,False
3,774,"mountain-100 silver, 48",Mountain Bikes,3399.99,False
4,775,"mountain-100 black, 38",Mountain Bikes,3374.99,False
...,...,...,...,...,...
290,930,hl mountain tire,Tires and Tubes,35.00,False
291,931,ll road tire,Tires and Tubes,21.49,False
292,932,ml road tire,Tires and Tubes,24.99,False
293,933,hl road tire,Tires and Tubes,32.60,False
294,934,touring tire,Tires and Tubes,28.99,False

# Why case normalization is mandatory

Case normalization is important because the same product name can appear with different capitalization, such as "Pro", "PRO", or "pro". Without converting the text to a consistent case, searches and filters may miss matching products.

Converting ProductName to lowercase ensures that text searches such as "pro" work consistently across the entire dataset. This improves data consistency, searching, filtering, and analysis.

# Task 3: The Compliance Scanner (Regex Pattern Extraction)

In [31]:
import pandas as pd

df = pd.DataFrame({
    "Support_Message": [
        "REF12345 user email john@example.com issue logged",
        "Ticket 67890 assigned to REF5678 contact jane@gmail.com",
        "REF99999 ticket 12345 email support@company.com"
    ]
})

df

                                     Support_Message
0  REF12345 user email john@example.com issue logged
1  Ticket 67890 assigned to REF5678 contact jane@...
2    REF99999 ticket 12345 email support@company.com

In [32]:
df["Ticket_ID"] = df["Support_Message"].str.findall(r"\d+")

df

                                     Support_Message       Ticket_ID
0  REF12345 user email john@example.com issue logged         [12345]
1  Ticket 67890 assigned to REF5678 contact jane@...   [67890, 5678]
2    REF99999 ticket 12345 email support@company.com  [99999, 12345]

In [33]:
df["REF_Code"] = df["Support_Message"].str.findall(r"^REF\w+")

df

,Support_Message,Ticket_ID,REF_Code
0,REF12345 user email john@example.com issue logged,[12345],[REF12345]
1,Ticket 67890 assigned to REF5678 contact jane@...,"[67890, 5678]",[]
2,REF99999 ticket 12345 email support@company.com,"[99999, 12345]",[REF99999]

In [34]:
df["Email"] = df["Support_Message"].str.findall(r"\w+@\w+\.\w+")

df

,Support_Message,Ticket_ID,REF_Code,Email
0,REF12345 user email john@example.com issue logged,[12345],[REF12345],[john@example.com]
1,Ticket 67890 assigned to REF5678 contact jane@...,"[67890, 5678]",[],[jane@gmail.com]
2,REF99999 ticket 12345 email support@company.com,"[99999, 12345]",[REF99999],[support@company.com]

# Regex Pattern Extraction

- `\d+` extracts numeric values from the support messages.
- `^REF\w+` extracts reference codes beginning with `REF`.
- `\w+@\w+\.\w+` extracts email addresses.

The extracted values were stored in separate columns: `Ticket_ID`, `REF_Code`, and `Email`.

# Task 4: The Data Sanitizer (Hybrid Cleaning Pipeline)

In [35]:
df.head()

,Support_Message,Ticket_ID,REF_Code,Email
0,REF12345 user email john@example.com issue logged,[12345],[REF12345],[john@example.com]
1,Ticket 67890 assigned to REF5678 contact jane@...,"[67890, 5678]",[],[jane@gmail.com]
2,REF99999 ticket 12345 email support@company.com,"[99999, 12345]",[REF99999],[support@company.com]

In [40]:
# Task 4: Data Sanitizer - Hybrid Cleaning Pipeline

# 1. Remove duplicate emails
df = df.drop_duplicates(subset="Email")

# 2. Convert text values to lowercase
def lowercase_values(x):
    if isinstance(x, str):
        return x.lower()
    elif isinstance(x, list):
        return [item.lower() if isinstance(item, str) else item for item in x]
    else:
        return x

text_cols = df.select_dtypes(include="object").columns
df[text_cols] = df[text_cols].apply(
    lambda col: col.map(lowercase_values)
)

# 3. Extract 10-digit phone numbers
import re

df["Phone_Number"] = df["Support_Message"].apply(
    lambda x: re.findall(r"\d{10}", x)
)

df

C:\Users\Darshan\AppData\Local\Temp\ipykernel_30704\2642259431.py:15: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_cols = df.select_dtypes(include="object").columns

,Support_Message,Ticket_ID,REF_Code,Email,Phone_Number
0,ref12345 user email john@example.com issue logged,[12345],[ref12345],[john@example.com],[]
1,ticket 67890 assigned to ref5678 contact jane@...,"[67890, 5678]",[],[jane@gmail.com],[]
2,ref99999 ticket 12345 email support@company.com,"[99999, 12345]",[ref99999],[support@company.com],[]

# Why order of operations matters

The order of cleaning operations is important because each step prepares the data for the next step. First, duplicate emails are removed so duplicate records do not affect the dataset. Next, text values are converted to lowercase to maintain consistent formatting. Finally, phone numbers are extracted using a regular expression from the cleaned text. Following a logical order helps produce consistent and model-ready data.

# Task 5: The Audit Validator (Quality Assurance Check)

In [44]:
# 1. Count duplicates after cleaning
df_check = df.copy()

# Convert list values to tuples so pandas can compare them
for col in df_check.columns:
    df_check[col] = df_check[col].apply(
        lambda x: tuple(x) if isinstance(x, list) else x
    )


duplicate_count = df_check.duplicated().sum()
print("Number of duplicate rows:", duplicate_count)


# 2. Verify lowercase transformation
lowercase_check = df["Support_Message"].apply(
    lambda x: x == x.lower()
)

print("All Support_Message values are lowercase:", lowercase_check.all())


# 3. Confirm no null Ticket IDs
null_ticket_ids = df["Ticket_ID"].isna().sum()

print("Number of null Ticket IDs:", null_ticket_ids)

Number of duplicate rows: 0
All Support_Message values are lowercase: True
Number of null Ticket IDs: 0

# How these checks prevent downstream failures

These quality checks help ensure that the cleaned dataset is reliable before it is used for further analysis or loaded into a data warehouse. Checking for duplicates prevents repeated records from affecting analysis and reports. Verifying lowercase transformation ensures consistent text formatting and avoids mismatches during text processing. Confirming that Ticket_ID values are not null ensures that every record can be uniquely identified and tracked. These checks help prevent incorrect analysis, broken data pipelines, and unreliable downstream results.